{% set name = "h5pickle" %}
{% set version = "0.4" %}
{% set sha256 = "76ec8bf05463ed4522188eda1b162641bdbf06754bb30787fcb1fadae7fe9329" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - h5py
    - cachetools

test:
  imports:
    - h5pickle

about:
  home: http://github.com/exteris/h5pickle
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Wrapper for h5py with pickle capabilities'

  description: |
    This module provides a wrapper for the h5py classes to allow pickling of
    h5py objects. Basically the arguments to the h5py.File call are saved, and
    a new file is opened when a Group, Dataset or File is unpickled. Ergo, this
    will only work well on shared filesystems, and for reading files (SWMR
    should be fine too).
  doc_url: https://github.com/exteris/h5pickle
  dev_url: https://github.com/exteris/h5pickle

extra:
  recipe-maintainers:
    - Exteris
