travis:
  secure:
    BINSTAR_TOKEN: GiRQtBVfGh7ioV4dPBKwh06/QtIP1CAeW690kSLOLxm0bRscz9OSJmBVFzDyyPMmOT25ocsbNfAEvEFHaoCAoKf/dHZZf/xUEVqi866/ToDIPPFayhOFFh+OtFZ4MTOwzkxqFdUqzbHpb/3lKBDFDi7KGkUApk72HjJO0BRJGzfA+oqZK9KBij5MoknPFuLmulWuSDV5avb41zwa+gEf7oiIgN3YrzC2nopKBO8XPKYGsWwd9apQUeXvDy1bsIKLLyqQKdmtW4ELgwnh8N/HaBzvw0g6B2LXRxCYZVGwwrJvGjOQRwsH9Y/TVdWmxiXyE5zrmxfjEMF6ojpIUgTON62Z8WqD2QCq9oWoZvFGG9DPGgDO9RChJjcgSyoMaCh4HF2o/9iRIyPLKtsjYmyv3GXIQrZkrdJxyFdI7KDqckU+UDUoPCuGyDdx3z75oiobVsupDT7dMJlN+J/HSD09kSc00ny3BUF6XfPvibZr9dDsnMsEYm+0mhmLiA89PYFka4WEv1nTcIkPjAhzZvyJG0YHZAhVqUrgHHsvpvjwF7irvRrZWNn9BGE3C5XHvu6orSE1VxltmlVRoTeKURs6gf8opUxfZi5Qnz2IJdzekxBuCgD7iMm3//6sTCbtc75aw5+V5WESE7DybrRxvTptzFHrQdop/kLHbNDHJEzXl7c=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
