travis:
  secure:
    BINSTAR_TOKEN: hE1WQZN/bhpdTJHb7mru/+UySGeBqJrF7qxuvlNEWAb6Bq4/dLRBNP77q8kAlCT/VbZEwcf0WrgPi9qRBmmd2krSRsyTFLzW5S7LDPBk8/LTXUDShMT+oO1r8FICd1kgZifjs2bze8X7ObUQC4V8tP5IF7UDjHFFdDlEps6rmXK3xTi2Avb2lYoUXqTSSqA2Aa+9CD6deoIZ6TIxaTQtzyYtuWyqeuWG92jcDh+qudJPepF4B9XXUA8CdxIsspsDnyi7yXtRWnY72+56JIY2aqAr/65P7yNpr89I7HTo166IQPNsYUa5u4Z/eSDUZerll6eU099+BlRFspCx5Rd+YX9Jcbubc20rtxtbFFztfQ7TXa1Ujw7WrjkISseP07yBMY0lTyfQe6UsUVKPWVrTbSvqTggH1HY8Y67ckZGc5JXntbWjMqYXyHyDVdajl+0NluQoW3HQgu6UvgrxZ9NG1Sr3Xl4mFFA7oU9cwH7n/7i9A8uvZGDbEPppASLPqX3bRGVyfshO+zFL4UsPFQU5weryhJh2ZFDycvvmK8SJ+NLYJK/70eoRuzHyrsmWEMhA4U0dhdAiD1Sz1VlyJ/cpSxZO9/rUVTrBlNR9Za5shFMeuBo3x8cvFNpxF/rE58gj1pX4LwJrUBX9/SHLrpCKi8LflcI9mmlQviuZGX1kFMU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
